version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8181:80"
    volumes:
      - .:/var/www/project
      - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  php:
    build:
      dockerfile: Dockerfile
      context: .docker/php-fpm
    volumes:
      - .:/var/www/project
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#TODO
#1 install composer and run it
#2 install mysql extension
